### ISSUE TITLE
Add OAS metadata to definition file.

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/openapi#27]
## I expect

- the definition file to have oas metadata

cc: @vlauciani

**Comment by ioggstream** [comment]
duplicate of #26

**Comment by vlauciani** [comment]
Hi @ioggstream 

I'm working on converting your definition to OAS; this is a validate example:
- https://github.com/INGV/openapi/blob/master/docs/definitions_teamdigitale.yaml
